### ISSUE TITLE
Missing chain PR-QBS

### ISSUE THREAD

**Issue by rapenne-s** [r001/mullvad-dns#1]
Hi,

I'm trying to help someone running Qubes OS 4.2 with mullvad who is using this repo to fix DNS problems.

However, by default, there are no chain PR-QBS and no table named "nat", it doesn't seem the scripts are creating them at all. Is something missing?

**Comment by r001** [comment]
Yes, on fedora-40 (maybe fedora-39) based kernels there is no more chain of PR-QBS.
Working on getting things right.

**Comment by r001** [comment]
@rapenne-s 

> Hi,
> 
> I'm trying to help someone running Qubes OS 4.2 with mullvad who is using this repo to fix DNS problems.
> 
> However, by default, there are no chain PR-QBS and no table named "nat", it doesn't seem the scripts are creating them at all. Is something missing?

Check out the newest version, it will work on Qubes 4.2.
